spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: "create-drop"
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.format_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud?useSSL=false
    username: root
    password: my-secret-pw